language: node_js

node_js:
  - '10.15.2'

sudo: required

git:
  quiet: true
  
cache:
  directories:
    - node_modules

branches:
  only:
    - hexocode

before_install:
  - git config --global user.name "DearSummer"
  - git config --global user.email "591243801@qq.com"
  - npm install -g hexo-cli

install:
  - npm install hexo-deployer-git --save
  - npm install


script:
  - hexo clean
  - hexo generate
 
after_script:
  - git config user.name "DearSummer"
  - git config user.email "591243801@qq.com"
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - hexo deploy


 
